import {Router} from "express";
import {container} from "tsyringe";
import {CustomerController} from "../controllers/customer.controller";
import {ControllerWrapper} from "../utils/controller.wrapper";
const router = Router();
const controller = container.resolve(CustomerController);
router.post('/', ControllerWrapper.wrap(controller, 'create'));
router.get('/', ControllerWrapper.wrap(controller, 'findAll'));
router.post('/:id', ControllerWrapper.wrap(controller, 'findById'));
router.delete('/:id', ControllerWrapper.wrap(controller, 'delete'));
export default router;