import {Router} from "express";
import {container} from "tsyringe";
import {CustomerController} from "../controllers/customer.controller";
import {ControllerWrapper} from "../utils/controller.wrapper";
const router = Router();
const controller = container.resolve(CustomerController);
router.post('/create', ControllerWrapper.wrap(controller, 'create'));
router.put('/update/:id', ControllerWrapper.wrap(controller, 'update'));
router.get('/findAll', ControllerWrapper.wrap(controller, 'findAll'));
router.post('/findById/:id', ControllerWrapper.wrap(controller, 'findById'));
router.delete('/delete/:id', ControllerWrapper.wrap(controller, 'delete'));
export default router;