import express from 'express';
import userRoutes from './routes/user.routes';
import loginRoutes from './routes/login.routes';
import cors from 'cors';
const app = express();
app.use(cors());
app.use(express.json());
app.use('/users', userRoutes);
app.use('/login', loginRoutes);
export default app;